local constants = require("utils.constants")
return {
  "mrjones2014/smart-splits.nvim",
  opts = {
    ignored_buftypes = constants.ignored_buftypes,
    ignored_filetypes = constants.ignore_filetypes,
  },
  keys = {
    {
      "<A-h>",
      "<cmd>lua require('smart-splits').resize_left(3)<cr>",
      desc = "Resize Split Left",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<A-j>",
      "<cmd>lua require('smart-splits').resize_down(3)<cr>",
      desc = "Resize Split Down",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<A-k>",
      "<cmd>lua require('smart-splits').resize_up(3)<cr>",
      desc = "Resize Split Up",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<A-l>",
      "<cmd>lua require('smart-splits').resize_right(3)<cr>",
      desc = "Resize Split Right",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<C-h>",
      "<cmd>lua require('smart-splits').move_cursor_left({same_row = true})<cr>",
      desc = "Move Cursor to Left Split",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<C-j>",
      "<cmd>lua require('smart-splits').move_cursor_down({same_row = true})<cr>",
      desc = "Move Cursor to Downward Split",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<C-k>",
      "<cmd>lua require('smart-splits').move_cursor_up({same_row = true})<cr>",
      desc = "Move Cursor to Upward Split",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<C-l>",
      "<cmd>lua require('smart-splits').move_cursor_right({same_row = true})<cr>",
      desc = "Move Cursor to Right Split",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader><leader>h",
      "<cmd>lua require('smart-splits').swap_buf_left({move_cursor = true})<cr>",
      desc = "Swap buffer in split on the left with buffer in current split",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader><leader>j",
      "<cmd>lua require('smart-splits').swap_buf_down({move_cursor = true})<cr>",
      desc = "Swap buffer in downward splits with buffer in current split",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader><leader>k",
      "<cmd>lua require('smart-splits').swap_buf_up({move_cursor = true})<cr>",
      desc = "Swap buffer in upward splits with buffer in current split",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader><leader>l",
      "<cmd>lua require('smart-splits').swap_buf_right({move_cursor = true})<cr>",
      desc = "Swap buffer in splits on the right with buffer in current split",
      silent = true,
      noremap = true,
      nowait = true,
    },
  },
}
