-- Surround with quotes, brackets and paranthesis
return {
  "kylechui/nvim-surround",
  version = "*",
  opts = {
    keymaps = {
      insert = "<C-g>s",
      insert_line = "<C-g>S",
      visual = "S",
      visual_line = "gS",
    },
  },
  keys = {
    {
      "<leader>ss",
      "<Plug>(nvim-surround-normal)",
      mode = "n",
      desc = "Add a surrounding pair around a motion (normal mode)",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>sc",
      "<Plug>(nvim-surround-normal-cur)",
      mode = "n",
      desc = "Add a surrounding pair around the current line (normal mode)",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>snl",
      "<Plug>(nvim-surround-normal-line)",
      mode = "n",
      desc = "Add a surrounding pair around a motion, on new lines (normal mode)",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>sncl",
      "<Plug>(nvim-surround-normal-cur-line)",
      mode = "n",
      desc = "Add a surrounding pair around a motion, on new lines (normal mode)",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>suc",
      "<Plug>(nvim-surround-change)",
      mode = "n",
      desc = "Change a surrounding pair",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>sul",
      "<Plug>(nvim-surround-change-line)",
      mode = "n",
      desc = "Change a surrounding pair, putting replacements on new lines",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>sd",
      "<Plug>(nvim-surround-delete)",
      mode = "n",
      desc = "Delete a surrounding pair",
      silent = true,
      noremap = true,
      nowait = true,
    },
  },
}
