return {
  -- "pmizio/typescript-tools.nvim",
  -- dependencies = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
  -- ft = { "typescript", "typescriptreact", "typescript.tsx", "javascriptreact", "javascript" },
  -- opts = {
  --   on_attach = require("utils.lsp.on_attach"),
  --   settings = {
  --     tsserver_file_preferences = {
  --       quotePreference = "double",
  --
  --       --[[ INLAYS ]]
  --       includeInlayEnumMemberValueHints = true,
  --       includeInlayFunctionLikeReturnTypeHints = true,
  --       includeInlayFunctionParameterTypeHints = true,
  --       includeInlayParameterNameHints = "all", -- 'none' | 'literals' | 'all';
  --       includeInlayParameterNameHintsWhenArgumentMatchesName = true,
  --       includeInlayPropertyDeclarationTypeHints = true,
  --       includeInlayVariableTypeHints = true,
  --     },
  --     tsserver_format_options = {
  --       tabSize = 4,
  --       convertTabsToSpaces = false,
  --       insertSpaceAfterCommaDelimiter = true,
  --       insertSpaceAfterFunctionKeywordForAnonymousFunctions = true,
  --       insertSpaceAfterKeywordsInControlFlowStatements = true,
  --       insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces = true,
  --       insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = true,
  --       insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets = true,
  --       insertSpaceAfterSemicolonInForStatements = true,
  --       insertSpaceBeforeAndAfterBinaryOperators = true,
  --       semicolons = "insert",
  --       trimTrailingWhitespace = true,
  --       newLineCharacter = "\n",
  --     },
  --   },
  -- },
}
