return {
  "lewis6991/gitsigns.nvim",
  event = { "BufReadPre", "BufNewFile" },
  config = function()
    local gitsigns = require("gitsigns")
    gitsigns.setup({
      preview_config = {
        border = "rounded",
        style = "minimal",
        relative = "cursor",
        row = 0,
        col = 1,
      },
    })
  end,
  keys = {
    {
      "<leader>gj",
      "<cmd>lua require('gitsigns').next_hunk()<cr>",
      desc = "Next Hunk",
      mode = "n",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>gk",
      "<cmd>lua require('gitsigns').prev_hunk()<cr>",
      desc = "Prev Hunk",
      mode = "n",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>gp",
      "<cmd>lua require('gitsigns').preview_hunk()<cr>",
      desc = "Preview Hunk",
      mode = "n",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>gr",
      "<cmd>lua require('gitsigns').reset_hunk()<cr>",
      desc = "Reset Hunk",
      mode = "n",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>gs",
      "<cmd>lua require('gitsigns').stage_hunk()<cr>",
      desc = "Stage Hunk",
      mode = "n",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>gu",
      "<cmd>lua require('gitsigns').undo_stage_hunk()<cr>",
      desc = "Undo Stage Hunk",
      mode = "n",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>gS",
      "<cmd>lua require('gitsigns').stage_buffer()<cr>",
      desc = "Stage Buffer",
      mode = "n",
      silent = true,
      noremap = true,
      nowait = true,
    },
    {
      "<leader>gR",
      "<cmd>lua require('gitsigns').reset_buffer()<cr>",
      desc = "Reset Buffer",
      mode = "n",
      silent = true,
      noremap = true,
      nowait = true,
    },
  },
}
