return {
  lsp = {
    "harper_ls",
    "ruff",
    "ts_ls",
    "texlab",
    "omnisharp",
    "sqlls",
    "lua_ls",
    "marksman",
    "eslint",
    "spectral",
    "jdtls",
    "cucumber_language_server",
    "clangd",
    "pyright",
  },
  dap = { "python", "js", "c#" },
  linters = { "cmakelint", "vale" },
  formatters = { "stylelua", "prettier", "cmake_format", "clang-format" },
}
